Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2024
var
    numero: real

inicio
    escreva("Digite um número: ")
    leia(numero)

    se (numero > 0) então
        escreva("O número é positivo.")
    fimse
   

Fimalgoritmo