Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2024
Var
// Seção de Declarações das variáveis 
  CONT : INTEIRO
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   CONT := 1
   ENQUANTO CONT <= 100 FACA
   ESCREVAL (CONT)
   CONT := CONT + 1
   FIMENQUANTO
    

Fimalgoritmo